version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "3000:3000"   # React dev server port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Hot reloading in Docker

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "9000:9000"   # Go server port
    volumes:
      - ./backend:/app
    environment:
      - PORT=9000
